# Welcome to Jekyll!

# Website settings
title: Anthea Li
description: Anthea's blog, use Jekyll and github pages.
keywords: Anthea Li 
baseurl:  /liych # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://antheali.github.io/site  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: AntheaLi  # Be used at blog posts' author.
  middle_name:  A foodie, a good cook and also a tech enthusiast for Deep Learning, Computer Vision, Computer Graphics, Augmented Reality, and Virual Reality. Currently a researcher working at the Boston University # Be used at index page about me section.
  first_name:
  last_name:  Also a freelance full-stack, iOS, Android developer. # Describe yourself.
  # Be used at index page about me section.
  avatar: /static/assets/img/landing/Avatar.png  # upload your avatar at directory and edit it.
  github_username: antheali # Leave blank if you don't have now
  linkedin_id: antheayichenli # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:  # Leave blank if you don't have now
  email: chentisch@gmail.com  # Leave blank if you don't have now
  cv: /static/assets/Resume_Yichen_Li.pdf  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name:
    - name: fa-code
    - name: icon-c
    - name: icon-csharp
    - name: icon-cplusplus
    - name: icon-haskell
    - name: icon-python
    - name: icon-unity
    - name: fa-android
    - name: icon-javascript
    - name: icon-reactjs
    - name: icon-java
  skill_icon2:
    - name: fa-user-secret
    - name: fa-connectdevelop
    - name: icon-angular
    - name: icon-ruby
    - name: icon-ghost
    - name: icon-mobile-device
    - name: icon-3dprint

  desc: #Tech enthusiast for Deep Learning, Computer Vision, Computer Graphics, Augmented Reality, and Virual Reality. Currently a researcher working at the Boston University Shape Lab run by Professor Whiting. Freelance full-stack, iOS, Android developer. # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-128485454-1

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

